version: '3.3'

services:
  arangodb:
    image: arangodb@sha256:664d8d8030845bcec5ae447d220cdb2b788f529211600e99e517bd7048aecaaf
    environment:
      - ARANGO_NO_AUTH=true
    volumes:
      - type: volume
        source: arangodb
        target: /var/lib/arangodb3
      - type: bind
        source: ./local/db/arangodb/entrypoint.sh
        target: /entrypoint.sh
      - type: bind
        source: ./local/db/arangodb/initdb.d
        target: /initdb.d
    ports:
      - "8529:8529"

volumes:
  arangodb: